/**
 * Chat Identity Utility
 * 
 * Provides deterministic chatId generation for 1-on-1 conversations.
 * Ensures duplicate-proof chat identity by sorting user IDs alphabetically.
 * 
 * RULES:
 * - chatId MUST be generated by sorting two userIds alphabetically
 * - Format: "userId1_userId2" where userId1 < userId2 (alphabetically)
 * - This ensures the same chatId is generated regardless of who initiates
 * 
 * @module features/messages/services/chatIdentity
 */

/**
 * Generate a deterministic chatId for a 1-on-1 conversation
 * 
 * @param userId1 - First user ID
 * @param userId2 - Second user ID
 * @returns Deterministic chatId in format "userId1_userId2" (sorted)
 * 
 * @example
 * ```typescript
 * buildChatId("alice", "bob")  // Returns: "alice_bob"
 * buildChatId("bob", "alice")  // Returns: "alice_bob" (same result!)
 * ```
 */
export function buildChatId(userId1: string, userId2: string): string {
    if (!userId1 || !userId2) {
        throw new Error('Both user IDs are required to build chatId');
    }

    if (userId1 === userId2) {
        throw new Error('Cannot create chat with self');
    }

    // Sort alphabetically to ensure deterministic ID
    const [first, second] = [userId1, userId2].sort();

    return `${first}_${second}`;
}

/**
 * Extract user IDs from a chatId
 * 
 * @param chatId - Chat ID in format "userId1_userId2"
 * @returns Array of [userId1, userId2]
 * 
 * @example
 * ```typescript
 * parseChatId("alice_bob")  // Returns: ["alice", "bob"]
 * ```
 */
export function parseChatId(chatId: string): [string, string] {
    if (!chatId || !chatId.includes('_')) {
        throw new Error('Invalid chatId format. Expected "userId1_userId2"');
    }

    const parts = chatId.split('_');

    if (parts.length !== 2) {
        throw new Error('Invalid chatId format. Expected exactly two user IDs');
    }

    return [parts[0], parts[1]];
}

/**
 * Get the other user's ID from a chatId
 * 
 * @param chatId - Chat ID in format "userId1_userId2"
 * @param currentUserId - Current user's ID
 * @returns The other user's ID
 * 
 * @example
 * ```typescript
 * getOtherUserId("alice_bob", "alice")  // Returns: "bob"
 * getOtherUserId("alice_bob", "bob")    // Returns: "alice"
 * ```
 */
export function getOtherUserId(chatId: string, currentUserId: string): string {
    const [userId1, userId2] = parseChatId(chatId);

    if (userId1 === currentUserId) {
        return userId2;
    } else if (userId2 === currentUserId) {
        return userId1;
    } else {
        throw new Error('Current user is not a participant in this chat');
    }
}

/**
 * Validate if a chatId is correctly formatted
 * 
 * @param chatId - Chat ID to validate
 * @returns true if valid, false otherwise
 */
export function isValidChatId(chatId: string): boolean {
    try {
        parseChatId(chatId);
        return true;
    } catch {
        return false;
    }
}
